// Generated by uniffi-bindgen-react-native
#include "react-native-zcam1-verify.h"
#include "generated/sp1_uniffi_verifier.hpp"

namespace zcam1verify {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSp1UniffiVerifier::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}