// Generated by uniffi-bindgen-react-native
// Modified: use fbjni cthis() instead of manual JNI field walking (RN 0.80+ compat)
#include <jni.h>
#include <jsi/jsi.h>
#include <fbjni/fbjni.h>
#include <ReactCommon/CallInvokerHolder.h>
#include "succinctlabs-react-native-zcam1-c2pa.h"

namespace jsi = facebook::jsi;
namespace jni = facebook::jni;
namespace react = facebook::react;

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_succinctlabs_reactnativezcam1c2pa_ReactNativeZcam1C2paModule_nativeInstallRustCrate(
    JNIEnv *env, jclass type, jlong rtPtr, jobject callInvokerHolderJavaObj
) {
    auto holder = jni::wrap_alias(callInvokerHolderJavaObj);
    auto callInvokerHolder = jni::static_ref_cast<react::CallInvokerHolder::javaobject>(holder);
    auto jsCallInvoker = callInvokerHolder->cthis()->getCallInvoker();

    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return succinctlabs_reactnativezcam1c2pa::installRustCrate(*runtime, jsCallInvoker);
}

extern "C"
JNIEXPORT jboolean JNICALL
Java_com_succinctlabs_reactnativezcam1c2pa_ReactNativeZcam1C2paModule_nativeCleanupRustCrate(JNIEnv *env, jclass type, jlong rtPtr) {
    auto runtime = reinterpret_cast<jsi::Runtime *>(rtPtr);
    return succinctlabs_reactnativezcam1c2pa::cleanupRustCrate(*runtime);
}
