// Generated by uniffi-bindgen-react-native
import installer from './NativeZcam1Sdk';

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from './generated/zcam1_c2pa_utils';
export * from './generated/zcam1_certs_utils';
export * from './generated/zcam1_proving_utils';
export * from './generated/zcam1_verifier';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as zcam1_c2pa_utils from './generated/zcam1_c2pa_utils';
import * as zcam1_certs_utils from './generated/zcam1_certs_utils';
import * as zcam1_proving_utils from './generated/zcam1_proving_utils';
import * as zcam1_verifier from './generated/zcam1_verifier';

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  zcam1_c2pa_utils.default.initialize();
  zcam1_certs_utils.default.initialize();
  zcam1_proving_utils.default.initialize();
  zcam1_verifier.default.initialize();
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  zcam1_c2pa_utils,
  zcam1_certs_utils,
  zcam1_proving_utils,
  zcam1_verifier,
};

