import type { Settings } from ".";
import { DeviceBindings } from "react-native-zcam1-c2pa";

/**
 * Generates a cryptographic proof for the given data hash using device bindings.
 *
 * This function requests a proof from the backend service and polls until the proof
 * is ready, then returns it as a Uint8Array.
 *
 * @param deviceBindings - The device-specific bindings including attestation, assertion, and key information
 * @param dataHash - The base64-encoded hash of the data to generate a proof for
 * @param settings - Application settings including the backend URL and production flag
 * @returns A promise that resolves to the generated proof as a Uint8Array
 * @throws Will throw an error if the proof request fails or proof generation fails
 */
export async function generateProof(
  deviceBindings: DeviceBindings,
  dataHash: string, // b64
  settings: Settings,
): Promise<Uint8Array> {
  const requestId = await requestProof(deviceBindings, dataHash, settings);

  console.log(`Requested proof: ${requestId}`);

  let proof = await getProof(requestId, settings);

  return proof;
}

/**
 * Retrieves the verification key hash from the backend service.
 *
 * This function fetches the verification key hash that can be used to verify
 * cryptographic proofs generated by the system.
 *
 * @param settings - Application settings including the backend URL
 * @returns A promise that resolves to the verification key hash as a string
 * @throws Will throw an error if the request fails
 */
export async function getVkHash(settings: Settings): Promise<String> {
  let response = await fetch(settings.backendUrl + `/ios/vk`);

  const vkHash = await response.text();

  return vkHash;
}

async function requestProof(
  deviceBindings: DeviceBindings,
  dataHash: string, // b64
  settings: Settings,
): Promise<string> {
  let response = await fetch(settings.backendUrl + "/ios/request-proof", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      attestation: deviceBindings.attestation,
      assertion: deviceBindings.assertion,
      keyId: deviceBindings.deviceKeyId,
      dataHash,
      appId: deviceBindings.appId,
      appAttestProduction: settings.production,
    }),
  });

  if (!response.ok) {
    throw "failed to request a proof:" + (await response.text());
  }

  return await response.text();
}

async function getProof(
  requestId: string,
  settings: Settings,
): Promise<Uint8Array> {
  while (true) {
    let response = await fetch(settings.backendUrl + `/ios/proof/${requestId}`);

    if (response.status === 200) {
      const arrayBuffer = await response.arrayBuffer();
      return new Uint8Array(arrayBuffer);
    } else if (response.status !== 202) {
      throw await response.text();
    }

    console.log(`Waiting for proof: ${requestId}`);
    await sleep(3000);
  }
}

async function sleep(duration: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, duration));
}
