// Generated by uniffi-bindgen-react-native
package com.succinctlabs.reactnativezcam1c2pa

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = ReactNativeZcam1C2paModule.NAME)
class ReactNativeZcam1C2paModule(reactContext: ReactApplicationContext) :
  NativeReactNativeZcam1C2paSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // succinctlabs-react-native-zcam1-c2pa.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  companion object {
    const val NAME = "ReactNativeZcam1C2pa"

    init {
      System.loadLibrary("succinctlabs-react-native-zcam1-c2pa")
    }
  }
}