// Generated by uniffi-bindgen-react-native
#include "react-native-zcam1-c2pa.h"
#include "generated/zcam1_c2pa_utils.hpp"

namespace zcam1c2pa {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeZcam1C2paUtils::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}