// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-zcam1-c2pa.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "Zcam1C2paSpec.h"

@interface Zcam1C2pa : NSObject <NativeZcam1C2paSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Zcam1C2pa : NSObject <RCTBridgeModule>
#endif

@end