// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-zcam1-verify.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "Zcam1VerifySpec.h"

@interface Zcam1Verify : NSObject <NativeZcam1VerifySpec>
#else
#import <React/RCTBridgeModule.h>

@interface Zcam1Verify : NSObject <RCTBridgeModule>
#endif

@end