add-yalc-to-e2e:
    yalc publish
    cd ../examples/e2e && yalc add @succinctlabs/react-native-zcam1-c2pa

add-yalc-to-capture-lib:
    yalc publish
    cd ../react-native-zcam1-capture && yalc add @succinctlabs/react-native-zcam1-c2pa

add-yalc-to-prove-lib:
    yalc publish
    cd ../react-native-zcam1-prove && yalc add @succinctlabs/react-native-zcam1-c2pa

add-yalc-to-verify-lib:
    yalc publish
    cd ../react-native-zcam1-verify && yalc add @succinctlabs/react-native-zcam1-c2pa

add-yalc-to-picker-lib:
    yalc publish
    cd ../react-native-zcam1-picker && yalc add @succinctlabs/react-native-zcam1-c2pa

publish $NPM_CONFIG_REGISTRY:
    npm publish --access public
    cd ../react-native-zcam1-capture && npm i @succinctlabs/react-native-zcam1-c2pa
    cd ../react-native-zcam1-prove && npm i @succinctlabs/react-native-zcam1-c2pa
    cd ../react-native-zcam1-verify && npm i @succinctlabs/react-native-zcam1-c2pa
    cd ../react-native-zcam1-picker && npm i @succinctlabs/react-native-zcam1-c2pa
