add-yalc-to-e2e:
    yalc publish
    cd ../examples/e2e && yalc add @succinctlabs/react-native-zcam1-c2pa

add-yalc-to-capture-lib:
    yalc publish
    cd ../react-native-zcam1-capture && yalc add @succinctlabs/react-native-zcam1-c2pa
