add-yalc-to-e2e:
    yalc publish
    cd ../examples/e2e && yalc add @succinctlabs/react-native-zcam1

add-yalc-to-android-test:
    yalc publish
    cd ../examples/android-test && yalc add @succinctlabs/react-native-zcam1-capture

publish $NPM_CONFIG_REGISTRY:
    npm publish --access public
