name: Zcam1-Sdk
rust:
  directory: ./..
  manifestPath: crates/bindings/Cargo.toml
turboModule:
  entrypoint: src/bindings.tsx
ios:
  frameworkName: Zcam1Framework
android:
  packageName: com.succinctlabs.zcam1sdk
  jniLibs: ../Zcam1Jni
noOverwrite:
  - "Zcam1Sdk.podspec"
  - "android/build.gradle"
  - "android/cpp-adapter.cpp"
  - "android/CMakeLists.txt"
