// Generated by uniffi-bindgen-react-native
import installer from "./NativeZcam1Proving";

if (installer === null) {
  throw new Error(
    "Failed to load the ZCAM1 proving feature.\n" +
      "If you use Expo, you need to add a plugin for `@succinctlabs/react-native-zcam1`" +
      "in you app.json with { 'enableProving': true }\n" +
      "If you use bare React Native, set the `ZCAM1_ENABLE_PROVING` env var to `1` \n" +
      "Finally you'll have to run `npx expo prebuild && cd ios && pod install`",
  );
}

// Register the rust crate with Hermes
// - the boolean flag ensures this loads exactly once, even if the JS
//   code is reloaded (e.g. during development with metro).
let rustInstalled = false;
if (!rustInstalled) {
  installer.installRustCrate();
  rustInstalled = true;
}

// Export the generated bindings to the app.
export * from "./../generated/zcam1_proving_utils";

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as zcam1_proving_utils from "./../generated/zcam1_proving_utils";

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - the boolean flag ensures this loads exactly once, even if the JS code
//   is reloaded (e.g. during development with metro).
let initialized = false;
if (!initialized) {
  zcam1_proving_utils.default.initialize();
  initialized = true;
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

// Export the crates as individually namespaced objects.
export default {
  zcam1_proving_utils,
};
