use serde::{Deserialize, Serialize};
use sp1_primitives::io::SP1PublicValues;
use sp1_stark::SP1Proof;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProofFromNetwork {
    pub proof: SP1Proof,
    pub public_values: SP1PublicValues,
    pub sp1_version: String,
}

impl ProofFromNetwork {
    pub fn as_bytes(&self) -> Vec<u8> {
        todo!()
    }
}

#[derive(Debug, Clone)]
pub enum SP1ProofMode {
    /// A proof generated by the core proof mode.
    ///
    /// The proof size scales linearly with the number of cycles.
    Core,
    /// A proof generated by the compress proof mode.
    ///
    /// The proof size is constant, regardless of the number of cycles.
    Compressed,
    /// A proof generated by the Plonk proof mode.
    Plonk,
    /// A proof generated by the Groth16 proof mode.
    Groth16,
}
