// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-zcam1-prove.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "Zcam1ProveSpec.h"

@interface Zcam1Prove : NSObject <NativeZcam1ProveSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Zcam1Prove : NSObject <RCTBridgeModule>
#endif

@end