// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/zcam1_c2pa_utils';
export * from './generated/zcam1_common';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as zcam1_c2pa_utils from './generated/zcam1_c2pa_utils';
import * as zcam1_common from './generated/zcam1_common';

import initAsync from './generated/wasm-bindgen/index.js';
import wasmPath from './generated/wasm-bindgen/index_bg.wasm';

export async function uniffiInitAsync() {
  await initAsync({ module_or_path: wasmPath })

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  // - the boolean flag ensures this loads exactly once, even if the JS code
  //   is reloaded (e.g. during development with metro).
  zcam1_c2pa_utils.default.initialize();
  zcam1_common.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  zcam1_c2pa_utils,
  zcam1_common,
};

