// Generated by uniffi-bindgen-react-native
// Export the generated bindings to the app.
export * from './generated/zcam1_c2pa_utils';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as zcam1_c2pa_utils from './generated/zcam1_c2pa_utils';

import initAsync from './generated/wasm-bindgen/index.js';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

export async function uniffiInitAsync() {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  // Dist layout: index_bg.wasm sits alongside this file.
  // Source layout: it lives under generated/wasm-bindgen/.
  const candidates = [
    join(__dirname, 'index_bg.wasm'),
    join(__dirname, 'generated/wasm-bindgen/index_bg.wasm'),
  ];
  const wasmPath = candidates.find((p) => { try { readFileSync(p); return true; } catch { return false; } })!;
  const wasmBytes = readFileSync(wasmPath);
  await initAsync({ module_or_path: wasmBytes });

  // Initialize the generated bindings: mostly checksums, but also callbacks.
  zcam1_c2pa_utils.default.initialize();
}

// Export the crates as individually namespaced objects.
export default {
  zcam1_c2pa_utils,
};
