// Generated by uniffi-bindgen-react-native
#include "react-native-zcam1-prove.h"
#include "generated/zcam1_proving_utils.hpp"

namespace zcam1prove {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeZcam1ProvingUtils::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}