name: Release iOS Frameworks

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release (e.g. 1.0.0)"
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Create the GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: ZCAM1 SDK v${{ github.event.inputs.version }}
          draft: true
          body: |
            # ZCAM1 SDK Release v${{ github.event.inputs.version }}

      - name: Publish react-native-zcam1-c2pa
        run: |
          cd react-native-zcam1-c2pa
          npm version ${{ github.event.inputs.version }}
          # npm publish
          npm run ubrn:ios
          zip -r Zcam1C2paFramework.xcframework.zip Zcam1C2paFramework.xcframework

      - name: Update the GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: |
            react-native-zcam1-c2pa/Zcam1C2paFramework.xcframework.zip
