name: Release ZCAM1 SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release (e.g. 1.0.0)"
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: macos-15

    steps:
      - name: Set up Xcode 16.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios,aarch64-apple-ios-sim

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}

      - name: Publish react-native-zcam1-c2pa
        run: |
          cd react-native-zcam1-c2pa
          npm ci
          npm version ${{ github.event.inputs.version }}
          # npm publish
          npm run ubrn:ios
          zip -r Zcam1C2paFramework.xcframework.zip Zcam1C2paFramework.xcframework

      - name: Add the framework to the GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          draft: true
          files: |
            react-native-zcam1-c2pa/Zcam1C2paFramework.xcframework.zip

      - name: Finalize the GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: ZCAM1 SDK v${{ github.event.inputs.version }}
